import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.GEMINI_API_KEY;

if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not defined in .env");
}

const ai = new GoogleGenAI({
    apiKey,
});

interface LowStockProduct {
    name: string;
    stock: number;
    price: number;
}

interface TopSellingProduct {
    name: string;
    totalQuantity: number;
    totalRevenue: number;
}

interface TopCustomer {
    name: string;
    email: string;
    totalOrders: number;
    totalSpent: number;
}

interface RequestedSales {
    totalOrders: number;
    totalRevenue: number;
}

interface RequestedProduct {
    name: string;
    stock: number;
    price: number;
}

interface RequestedProductSales {
    totalQuantity: number;
    totalRevenue: number;
}
export const askAI = async (
    message: string,
    data: {
        lowStockProducts: LowStockProduct[];
        topSellingProducts: TopSellingProduct[];
        topCustomers: TopCustomer[];
        requestedPeriod: string;
        requestedSales: RequestedSales;
        requestedProduct: RequestedProduct | null;
        requestedProductSales: RequestedProductSales;
    }
): Promise<string> => {

    const prompt = `
You are BizPilot AI, a concise business assistant.

Answer the user's question in ONLY 1 or 2 short sentences.
Use very simple language.
Do not use markdown.
Do not use headings.
Do not use bullet points.
Do not give unnecessary examples.

LOW STOCK PRODUCTS:
${JSON.stringify(data.lowStockProducts)}

TOP SELLING PRODUCTS:
${JSON.stringify(data.topSellingProducts)}

TOP CUSTOMERS:
${JSON.stringify(data.topCustomers)}

REQUESTED SALES PERIOD:
${data.requestedPeriod}

REQUESTED PERIOD SALES:
${JSON.stringify(data.requestedSales)}

REQUESTED PRODUCT:
${JSON.stringify(data.requestedProduct)}

REQUESTED PRODUCT SALES:
${JSON.stringify(data.requestedProductSales)}

Use the relevant data to answer the user's question.

If the user asks about sales for a specific time period,
use REQUESTED PERIOD SALES.

If the user asks about a specific product, use REQUESTED PRODUCT data.
If REQUESTED PRODUCT is null, clearly say that the product was not found.
Do not invent product information.

If the user asks how many units of a specific product were sold, use REQUESTED PRODUCT SALES.
If the user asks about revenue generated by a specific product, use REQUESTED PRODUCT SALES.
Do not invent product sales data.

Do not invent or make up business data.

User question:
${message}
`;

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
    });

    return response.text ?? "";
};
